Added privileges check in the update-script.

diff --git a/scripts/update-script b/scripts/update-script
--- a/scripts/update-script
+++ b/scripts/update-script
@@ -23,6 +23,20 @@
 ##
 # check for root / sudoers rights
 ##
+if [[ $EUID -ne 0 ]]; then
+	sudo -v > /dev/null;
+	if [[ $? -ne 0 ]]; then
+		echo "sorry, but you are neither root nor have sudo privileges. You cannot run this script successfully."
+		echo "exiting... try with another user."
+		exit;
+	else
+		PRIV='sudo ';
+	fi
+else
+	PRIV='';
+fi
+
+echo $PRIV
 
 ##
 # parse args
